# Generated by Django 4.2.13 on 2024-06-15 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.BooleanField()),
                ('caption_ref', models.CharField(max_length=255, null=True)),
                ('prompt_ref', models.CharField(max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('post_visibility', models.CharField(choices=[('PR', 'Private'), ('FO', 'Followers Only'), ('PU', 'Public')], default='PR', max_length=2)),
                ('prompt_visibility', models.CharField(choices=[('PR', 'Private'), ('FO', 'Followers Only'), ('PU', 'Public')], default='PR', max_length=2)),
                ('ref_post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_post', to='post.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='PromptedMediaRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompted_media_ref', models.CharField(max_length=255, unique=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompted_media_ref', to='post.post')),
            ],
            options={
                'db_table': 'prompted_media_ref',
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(choices=[('HAT', 'Hate'), ('HAR', 'Harassment'), ('VIS', 'Violent Speech'), ('CHS', 'Child Safety'), ('PRI', 'Privacy'), ('SPA', 'Spam'), ('SEH', 'Self Harm'), ('SEM', 'Sensitive Media'), ('IMP', 'Impersonation'), ('VIE', 'Violent Entities'), ('IPV', 'Intellectual Property Violation'), ('OTH', 'Other')], max_length=3)),
                ('user_report', models.CharField(max_length=255, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_report', to='post.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_report',
            },
        ),
        migrations.CreateModel(
            name='GenMediaRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_media_ref', models.CharField(max_length=255, unique=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_media_ref', to='post.post')),
            ],
            options={
                'db_table': 'gen_media_ref',
            },
        ),
    ]
