# Generated by Django 4.2.13 on 2024-06-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image_text_ref_alter_post_prompt_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_text_ref',
        ),
        migrations.CreateModel(
            name='ImageTextRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text_ref', models.CharField(max_length=255, unique=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='post.post')),
            ],
            options={
                'db_table': 'image_text_ref',
            },
        ),
    ]
