# Generated by Django 4.2.13 on 2024-06-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_image_text_ref_imagetextref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetextref',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_text_ref', to='post.post'),
        ),
    ]
