# Generated by Django 4.2.13 on 2024-06-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_imagetextref_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
