# Generated by Django 4.2.13 on 2024-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_ref', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'media_genre',
                'unique_together': {('media_ref', 'genre')},
            },
        ),
    ]
