# Generated by Django 4.2.13 on 2024-06-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocked_by_user_id', 'blocked_user_id')},
        ),
    ]
