# Generated by Django 4.2.13 on 2024-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='accept_timestamp',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
