# Generated by Django 4.2.13 on 2024-06-17 02:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('post_id', 'user_id')},
        ),
    ]
