# Generated by Django 4.2.13 on 2024-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='Subject', max_length=255),
            preserve_default=False,
        ),
    ]
