# Generated by Django 4.2.13 on 2024-08-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationEndpointArn',
        ),
    ]
